/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/fire.glb
*/

import React, { useRef, useMemo } from "react";
import { useGLTF, Sparkles } from "@react-three/drei";
import { useLoader, useFrame } from "@react-three/fiber";
import * as THREE from "three";

const ATLAS_COLS = 15;
const ATLAS_ROWS = 10;
const TOTAL_FRAMES = 150;
const FRAME_DURATION = 50; // ms per frame

function useFlameAtlas(atlasPath) {
  const texture = useLoader(THREE.TextureLoader, atlasPath);

  useMemo(() => {
    texture.wrapS = THREE.ClampToEdgeWrapping;
    texture.wrapT = THREE.ClampToEdgeWrapping;
    texture.repeat.set(1 / ATLAS_COLS, 1 / ATLAS_ROWS);
    texture.offset.set(0, 1 - 1 / ATLAS_ROWS);
  }, [texture]);

  return texture;
}

function FlameSprite({ nodes, nodeName, atlasPath, emissiveColor, emissiveIntensity, position, rotation, scale, children }) {
  const meshRef = useRef();
  const frameRef = useRef(0);
  const elapsedRef = useRef(0);
  const texture = useFlameAtlas(atlasPath);

  useFrame((_, delta) => {
    elapsedRef.current += delta * 1000;
    if (elapsedRef.current >= FRAME_DURATION) {
      elapsedRef.current = 0;
      frameRef.current = (frameRef.current + 1) % TOTAL_FRAMES;

      const col = frameRef.current % ATLAS_COLS;
      const row = Math.floor(frameRef.current / ATLAS_COLS);
      texture.offset.set(
        col / ATLAS_COLS,
        1 - (row + 1) / ATLAS_ROWS
      );
    }
  });

  return (
    <mesh
      ref={meshRef}
      name={nodeName}
      geometry={nodes[nodeName].geometry}
      position={position}
      rotation={rotation}
      scale={scale}
    >
      <meshStandardMaterial
        color="black"
        emissive={emissiveColor}
        emissiveMap={texture}
        emissiveIntensity={emissiveIntensity}
        alphaMap={texture}
        transparent
        depthWrite={false}
      />
      {children}
    </mesh>
  );
}

export function Fire(props) {
  const group = useRef();
  const lightRef = useRef();
  const { nodes, materials } = useGLTF("/3d/fire.glb");

  useFrame(() => {
    if (lightRef.current) {
      lightRef.current.intensity = 1 + 0.1 * Math.sin(Date.now() * 0.01);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <pointLight
          ref={lightRef}
          name="bonfire_light"
          intensity={1}
          decay={2}
          color="#ff7c2f"
          position={[-1.164, -0.584, 1.373]}
        />
        <FlameSprite
          nodes={nodes}
          nodeName="Flame"
          atlasPath="textures/red_flame_atlas.png"
          emissiveColor="blue"
          emissiveIntensity={50}
          position={[-1.174, -0.623, 1.38]}
          scale={0.413}
        />
        <FlameSprite
          nodes={nodes}
          nodeName="Flame001"
          atlasPath="textures/yellow_flame_atlas.png"
          emissiveColor="orange"
          emissiveIntensity={10}
          position={[-1.167, -0.673, 1.38]}
          rotation={[0.244, 0, 0]}
          scale={0.544}
        />
        <FlameSprite
          nodes={nodes}
          nodeName="Flame002"
          atlasPath="textures/white_flame_atlas.png"
          emissiveColor="white"
          emissiveIntensity={10}
          position={[-1.146, -0.552, 1.365]}
          rotation={[0.244, 0, 0]}
          scale={0.699}
        >
          <Sparkles count={50} speed={0.5} size={1} scale={1} noise={4} color="orange" />
        </FlameSprite>
        <mesh
          name="Cylinder084"
          geometry={nodes.Cylinder084.geometry}
          material={materials.fire_log}
          position={[-1.184, -0.843, 1.42]}
          rotation={[1.78, 0, 0]}
          scale={[0.057, 0.245, 0.051]}
        />
        <mesh
          name="Cylinder085"
          geometry={nodes.Cylinder085.geometry}
          material={materials.fire_log}
          position={[-1.214, -0.843, 1.293]}
          rotation={[-1.775, 0, 0]}
          scale={[0.057, 0.245, 0.051]}
        />
        <mesh
          name="Cylinder086"
          geometry={nodes.Cylinder086.geometry}
          material={materials.fire_log}
          position={[-1.232, -0.825, 1.369]}
          rotation={[1.563, 0.209, 1.608]}
          scale={[0.057, 0.245, 0.051]}
        />
        <mesh
          name="Cylinder087"
          geometry={nodes.Cylinder087.geometry}
          material={materials.fire_log}
          position={[-1.104, -0.843, 1.344]}
          rotation={[-1.563, 0.204, -1.608]}
          scale={[0.057, 0.245, 0.051]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d/fire.glb");
